q: batchq

# If zap_files: 1 then infiles for the function will deletec where specified
zap_files: 1

trimgalore:
    q: 5
    options: --stringency 3 --length 25

star:
    threads: 12
    ref: /t1-data/user/jakobsen/genomes/Homo_sapiens/Ensembl/GRCh38/STAR_with_ERCC_and_GTF/
    
picard:
    ref: /databank/igenomes/Homo_sapiens/Ensembl/GRCh38/Sequence/WholeGenomeFasta/genome_with_ERCC.fasta
        
featurecounts:
    gtf: /databank/igenomes/Homo_sapiens/Ensembl/GRCh38/Annotation/Homo_sapiens.GRCh38.86.with_ERCC.gtf
    options: --primary
