q: batch

# If zap_files: 1 then infiles for the function will deleted where specified
zap_files: 1

# FASTQ input files
# Links to fastq files need to be in a directory called "fastq\"
# There are two options:
# SE_demultiplexed: single-end reads with file extension in the format: R1_001.fastq.gz
# PE_barcoded: paired-end reads where Read 1 is the cell barcode with file extension in the format: L00[1-4]_R[1-2]_001.fq.gz

input: PE_barcoded
# Lanes: 'merged' or 'split'. If split, the pipeline will merge lanes
lanes: single

# Mapping
# If PE_barcoded, map using just "read2" or "both"
mapping: read2

cutadapt:
    barcodes: barcodes.fasta
    q: 15
    options: --minimum-length :25 --pair-filter=any
# If PE_novogene the pipeline also needs a barcodes.fasta file with cell barcodes

star:
    threads: 1
    ref: /t1-data/project/vyaslab/jakobsen/genomes/Homo_sapiens/Ensembl/GRCh38/STAR_2.7.7a_with_ERCC_filtered_GTF
    
picard:
    ref: /t1-data/project/vyaslab/jakobsen/genomes/Homo_sapiens/Ensembl/GRCh38/WholeGenomeFasta/Homo_sapiens.GRCh38.dna.primary_assembly_with_ERCC92.fa
        
featurecounts:
    gtf: /t1-data/project/vyaslab/jakobsen/genomes/Homo_sapiens/Ensembl/GRCh38/Annotation/Homo_sapiens.GRCh38.102.filtered.with_ERCC92.gtf
     # -s 1 means stranded couting
    options: --primary --extraAttributes gene_name -s 1
    # Memory needed is roughly 1/10th of the input fastq.qz size - 600Gb needs about 65G
    # This is per thread, so for 4 threads, it is a quarter
    memory: 20G
