q: batchq

# If zap_files: 1 then infiles for the function will deletec where specified
zap_files: 1

trimgalore:
    q: 5
    options: --stringency 3 --length 25

star:
    threads: 12
    ref: /t1-data/user/jakobsen/genomes/Homo_sapiens/Ensembl/GRCh38/STAR_with_ERCC_and_GTF/
    
picard:
    ref: /t1-data/user/jakobsen/genomes/Homo_sapiens/Ensembl/GRCh38/WholeGenomeFasta/Homo_sapiens.GRCh38.dna.primary_assembly_with_ERCC92.fa
        
featurecounts:
    gtf: /t1-data/user/jakobsen/genomes/Homo_sapiens/Ensembl/GRCh38/Annotation/Homo_sapiens.GRCh38.98.with_ERCC92.gtf
    options: --primary --extraAttributes gene_name
